name: Backup Routine
on:
  repository_dispatch:
    types: backup
  push:
    branches:
      - main
jobs:
  backup-dataset:
    runs-on: ubuntu-18.04
    name: Backup dataset
    steps:
      - uses: actions/checkout@v2
      - name: Export dataset
        uses: sanity-io/github-action-sanity@v0.2-alpha
        env:
          SANITY_AUTH_TOKEN: skn0WP3ITuMTlqEgrfhXctwPsJJZH8ItBgbzCJVfD26LVJWERGr1hVTGUz8BKF8tTVBkb0YroehBESKKlQ2m5lPiK7eQqUtZojjxvvprRDl9QEsO77PKD88xzfIIVgfgON1hFd03n53o9wRm4OrrDpvvy26EqJmqGhW4UlNvKtR9UWFwuqHo
        with:
          args: dataset export production backup.tar.gz
      - name: Upload backup.tar.gz
        uses: actions/upload-artifact@v2
        with:
          name: backup-tarball
          path: backup.tar.gz
          # Fails the workflow if no files are found; defaults to 'warn'
          if-no-files-found: error

  upload:
    runs-on: ubuntu-latest
    name: Upload to Dropbox
    needs: [backup-dataset]
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: yarn
      - name: Upload backup to Dropbox
        uses: ./
        with:
          DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
          DROPBOX_DESTINATION_PATH_PREFIX: "ES-MX"
          DEBUG: true
          GIT_KEY: ${{ secrets.GIT_KEY }}
